### ISSUE TITLE
Pipe shared memory to ffmpeg

### ISSUE THREAD

**Issue by jazzup** [remcoros/Direct3DCapture#1]
I'm using DXHookD3D9Obs.cs to capture video. I set up a keyboard hook. One key to hook and display fps and another to start/stop video capture. I know frames are captured and streamed because fps dip and hover around 30, sometimes less depending on the game.

I'm trying to pipe this stream to ffmpeg to process the video, ffmpeg provides "image2pipe" and accepts .bmp and .jpg + other formats. Is there a way to convert this stream to eiher formats.

In another project I was capturing directly (no shared memory) and using a binary writer and piping its stream to ffmpg. This caused fps to dip a lot.

**Comment by remcoros** [comment]
I have no experience with ffmpeg, but I suppose it's doable.

DXHookD3D9Obs saves the captured frames in a shared memory page (memory mapped file), which are the raw pixels. You can probably stream this to ffmpeg.

I have no client code for this capture engine, except a modified version in this application:

https://github.com/HearthstoneTracker/HearthstoneTracker/blob/master/HearthCap.Core/GameCapture/AutoCaptureEngine.cs#L742

Maybe it is of some help.

**Comment by jazzup** [comment]
Thanks. I'm downloading the hearthstone tracker project and will take a closer look.

**Comment by jazzup** [comment]
I altered the code to capture video at different resolutions and fed the images to ffmpeg successfully.

At 360p it's a solid 60 fps, at 720p it's mid 50's and upward and at my monitor's native resolution (1280x1024, yeah still on an old one) it's high 40's / low 50's, all settings on highest.

In DXHookD3D9Obs, you've set a targetFps to cap frame capture. If one caps the game itself to 30 fps (only during video capture), then it would be possible to capture video at higher resolutions without seeing dropped frames.

In directx 10 and 11, calling Present with a syncInterval of 2 caps the game's fps to 30. I've partially started video capture on dx10/11. In directx 9, I set PresentationInterval to Two at device creation time but saw no effect.

I'm still learning directx and I could be wrong but perhaps it is an approach you may want to consider when you implement video capture in hearthstone tracker in the future.

Cheers

**Comment by remcoros** [comment]
I have not really looked into screen recording (at least, not the outputting part) as there exists free tools (OBS :p) which do this really really well.

OBS for example, is optimized to use a DirectX device for rendering / filtering / processing, so it actually uses your GPU instead of ram/cpu. Also, their DX10/11 versions are way more advanced then the DX9 version.

I will probably never look into this, as I think, if people want to stream/record video, they could use OBS :-)

(and for hearthstonetracker, I'm completely moving away from screen capture eventually).

Thanks for the comments though, I bet someone could use this in the future.

**Comment by jazzup** [comment]
Thanks remcoros, OBS does a great job and I use it already.
Please, feel free to close this issue.
